# Generated by Django 3.0.8 on 2020-07-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportScanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filepath',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(default='1', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
