# Generated by Django 3.0.8 on 2020-07-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportScanner', '0002_auto_20200715_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.FileField(upload_to='post_images'),
        ),
    ]
