# Generated by Django 3.0.8 on 2020-07-15 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportScanner', '0003_auto_20200715_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
